### ISSUE TITLE
 If I go to ~/ I get error

### ISSUE THREAD

**Issue by tharyThary** [X3eRo0/dired.nvim#1]
![image](https://user-images.githubusercontent.com/71435013/178207471-e0c8da26-04f3-4623-b77d-badb55445a33.png)
After "Enter"
![image](https://user-images.githubusercontent.com/71435013/178207515-259bc161-2215-46b7-98bc-1b87c44f1fd8.png)

**Comment by X3eRo0** [comment]
Hey,
Can you post the output of "ls -lash ~/". for some reason one of the file is causing an issue. output of ls will help me understand the issue. Thanks

**Comment by tharyThary** [comment]
No :) but command has correct output and does not make errors

**Comment by X3eRo0** [comment]
How am I supposed to reproduce the bug. I need to know what kind of file is causing this issue.

**Comment by tharyThary** [comment]
Ok. This is output
![image](https://user-images.githubusercontent.com/71435013/178209277-990faced-3650-4f70-ba2a-e6cdd6ae31e5.png)

**Comment by X3eRo0** [comment]
Thanks @tharyThary :-)

**Comment by X3eRo0** [comment]
@tharyThary I pushed some changes can you post the output after updating the plugin?

**Comment by tharyThary** [comment]
![image](https://user-images.githubusercontent.com/71435013/178211591-5bfb87cf-3ce7-4fad-86bd-3ad988d9cbb4.png)

**Comment by tharyThary** [comment]
But this commands working

**Comment by X3eRo0** [comment]
> 

Got it. I will not try to reproduce.

**Comment by X3eRo0** [comment]
> This error seems to occur when editing a directory with lots of files and directories inside. `:e ~/`, `:e /home/wieerd`, `:e /usr/bin` all produced same error.

On my machine /usr/bin loads perfectly and for really large directories I created a folder with 99999 folders inside and my neovim was able to load that as well after getting stuck for 5 seconds.

huge_folder:
![image](https://user-images.githubusercontent.com/24680989/178215423-1df13e74-eb3d-424e-9051-10de24a0754a.png)

/usr/bin:
![image](https://user-images.githubusercontent.com/24680989/178215498-3d112750-34fd-42d6-9b15-25d6185cf736.png)

**Comment by X3eRo0** [comment]
@WieeRd can you post the output of "ls -lash ~/" or "ls -lash /usr/bin" in a pastebin or something? It will help me. Thanks :)

**Comment by X3eRo0** [comment]
@tharyThary please check if the issue has been resolved or not? I made some changes to the directory scanning function.
On my system, dired.nvim crashed when browsing a folder with a broken symlink. Now that is fixed in [771baee](https://github.com/X3eRo0/dired.nvim/commit/771baeeec6c086b54eb0b52da68fd80c7f718a34)

**Comment by X3eRo0** [comment]
@tharyThary also had broken symlinks by steam. Lmao.
