### ISSUE TITLE
Can't be loaded

### ISSUE THREAD

**Issue by shadyalfred** [X3eRo0/dired.nvim#3]
```
E5113: Error while calling lua chunk: ...vim/site/pack/packer/start/dired.nvim/lua/dired/init.lua:104: Vim(autocmd):E216: No such group or event: FileExplorer *
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/start/dired.nvim/lua/dired/init.lua:104: in function 'setup'
        
```
Neovim version: `NVIM v0.7.2`

```
    use {
        'X3eRo0/dired.nvim',
        requires = 'MunifTanjim/nui.nvim'
    }
```
```
require('dired').setup {
  path_separator = '/',
  show_banner = false,
  show_hidden = true
}
```

Maybe it is a conflict with `nvim-tree`?

**Comment by luisvgs** [comment]
Mine doesn't open as well. Not even recognize the `:Dired` command, even though is in fact installed.

**Comment by X3eRo0** [comment]
@shadyalfred @luisvgs please check if [6f9bd6c](https://github.com/X3eRo0/dired.nvim/commit/6f9bd6cc03a83bf3d8769828ace06b1a463b9d0b) fixed the bug or not?

**Comment by luisvgs** [comment]
> @shadyalfred @luisvgs please check if [6f9bd6c](https://github.com/X3eRo0/dired.nvim/commit/6f9bd6cc03a83bf3d8769828ace06b1a463b9d0b) fixed the bug or not?

It complains that `No such group or event: FileExplorer * stack traceback: [C] in function 'cmd'`

**Comment by X3eRo0** [comment]
I am not able to reproduce this. I will try installing nvim-tree or something and see if I can replicate this. Otherwise we will rollback to previous commit.

**Comment by luisvgs** [comment]
> I am not able to reproduce this. I will try installing nvim-tree or something and see if I can replicate this. Otherwise we will rollback to previous commit.

I don't have `nvim-tree` installed. Is it required to use this plugin? Thanks in advance. I'm very interested in use your plugin, I find it quite handy.

**Comment by X3eRo0** [comment]
No nvim-tree isn't required but the original author said he had it installed. Anyways can you tell me which other file browsing plugin is also installed in your config?

**Comment by luisvgs** [comment]
> No nvim-tree isn't required but the original author said he had it installed. Anyways can you tell me which other file browsing plugin is also installed in your config?

I don't have any other file browsing plugin! What I found quite confusing is the error it shows. Here is a more detailed description if it helps:

```E5113: Error while calling lua chunk: ...vim/site/pack/packer/start/dired.nvim/lua/dired/init.lua:105: Vim(autocmd):E216: No such group or event: FileExplorer *
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/start/dired.nvim/lua/dired/init.lua:105: in function 'setup'
        /home/luis/.config/nvim/init.lua:21: in main chunk```

**Comment by X3eRo0** [comment]
Did you update the plugin by running PackerSync or whatever plugin manager you use?

**Comment by luisvgs** [comment]
> Did you update the plugin by running PackerSync or whatever plugin manager you use?

I did. Also reinstalled and executed `PackerCompile`. I will check later tonight in my laptop to see if I can reproduce the same issue, I'm currently at my desktop machine.

**Comment by shadyalfred** [comment]
Still the same issue after updating

```
E5113: Error while calling lua chunk: ...vim/site/pack/packer/start/dired.nvim/lua/dired/init.lua:105: Vim(autocmd):E216: No such group or event: FileExplorer *
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/start/dired.nvim/lua/dired/init.lua:105: in function 'setup'
```
Dired command isn't defined too as @luisvgs said

**Comment by shadyalfred** [comment]
Commenting out line 105 in init.lua fixes the problem. However, when I press enter on a directory in Dired it opens this directory in nvim-tree instead

**Comment by mcauley-penney** [comment]
I'm having this issue too and it *appears* like Dired isn't checking for whether the group already exists or creating it itself. Creating the augroup "FileExplorer" solves it for me. For example, in the module in my configuration that I use to load autocommands, I used 

```lua
grp = vim.api.nvim_create_augroup("FileExplorer", { clear = true })
```

and the error disappears.

**Comment by luisvgs** [comment]
@mcauley-penney's workaround solves the problem for me!

**Comment by X3eRo0** [comment]
@luisvgs @mcauley-penney please check if [fefb17f](https://github.com/X3eRo0/dired.nvim/commit/fefb17f761f4018f78345fd158329999255e51b5) fixes the issue?

**Comment by X3eRo0** [comment]
I cannot replicate this issue. Makes it harder to fix. Your solution of creating a FileExplorer augroup solves the problem but I don't know why that works though.

**Comment by shadyalfred** [comment]
Doesn't the augroup `FileExplorer` exist by default?

```vimhelp
						*FileExplorer*
There is one group that is recognized by Vim: FileExplorer.  If this group
exists Vim assumes that editing a directory is possible and will trigger a
plugin that lists the files in that directory.  This is used by the |netrw|
plugin.  This allows you to do: >
	browse edit
```

**Comment by X3eRo0** [comment]
@mcauley-penney @shadyalfred check now?

**Comment by shadyalfred** [comment]
@X3eRo0 Works well now, thank you 🙏🏼

**Comment by X3eRo0** [comment]
ahhhhh, I can sleep now 💯

**Comment by luisvgs** [comment]
Yep, it works now!
