### ISSUE TITLE
Any chance to support Wdired mode?

### ISSUE THREAD

**Issue by hongxuchen** [X3eRo0/dired.nvim#4]
What I live most in Emacs is the capability to bulk editing file names in the so-called [Wdired mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Wdired.html). Is it possible to equipt dired.nvim with this mode?

**Comment by X3eRo0** [comment]
Wdired mode is definitely on the todo list. Its going to take a lot of work and I am on a tight schedule. Feel free to create a pull request.

I might work on this in the future but not in the near future.

**Comment by hongxuchen** [comment]
That will be great! 
I will read the code and see whether I could implement such a feature.
