### ISSUE TITLE
Group is shown as <NULL> in macOS

### ISSUE THREAD

**Issue by ronisbr** [X3eRo0/dired.nvim#8]
Hi!

Thanks for the plugin!

For some reason, the group is shown as `<NULL>` in macOS:

<img width="742" alt="Captura de Tela 2023-10-28 às 11 55 59" src="https://github.com/X3eRo0/dired.nvim/assets/1068295/8805df9b-3f6b-4fb9-847b-40e229009d0e">

<img width="660" alt="Captura de Tela 2023-10-28 às 11 56 15" src="https://github.com/X3eRo0/dired.nvim/assets/1068295/4223e08e-1883-4191-93a5-3d5098a2c6ef">

**Comment by ronisbr** [comment]
The problem is that `id -ng <GID>` does not return the group name related with GID in macOS.

**Comment by X3eRo0** [comment]
Got it. I will try and use my friend's Mac to reproduce it and try to fix it. Btw I have to say I like your neovim config. 😁

**Comment by ronisbr** [comment]
Thanks! :)

To help you, I manage to create a command to retrieve the group from the GID but I have no idea how "stable" it is:

```
grep ":20:[^:]*$" /etc/group | cut -d ":" -f1
```

**Comment by X3eRo0** [comment]
I didnt mean to close it. Can you check if its fixed?? @ronisbr
